name: Check Formatting

on: [push]

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      
      - name: Terraform Format
        id: fmt
        run:         
           terraform fmt -recursive
     
